# Generated by Django 5.1.15 on 2026-05-26 18:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('hosts', '0001_initial'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('repo_url', models.URLField(blank=True)),
                ('sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('regulated', 'Regulated')], default='internal', max_length=16)),
                ('local_paths', models.JSONField(blank=True, default=dict)),
                ('allowed_runtimes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_accounts', models.ManyToManyField(blank=True, related_name='allowed_projects', to='accounts.account')),
                ('allowed_hosts', models.ManyToManyField(blank=True, related_name='allowed_projects', to='hosts.host')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='policies.policyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
