# Generated by Django 5.1.15 on 2026-05-26 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('thread_create', 'Thread Create'), ('message_send', 'Message Send'), ('approval_request', 'Approval Request'), ('approval_grant', 'Approval Grant'), ('policy_block', 'Policy Block'), ('command_classify', 'Command Classify'), ('runtime_start', 'Runtime Start'), ('runtime_stop', 'Runtime Stop'), ('redaction', 'Redaction')], max_length=32)),
                ('redacted_payload', models.JSONField(default=dict)),
                ('raw_payload_encrypted', models.BinaryField(blank=True, null=True)),
                ('raw_retention_expires_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='threads.thread')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type'], name='audit_audit_event_t_04511c_idx'), models.Index(fields=['actor'], name='audit_audit_actor_5626f5_idx'), models.Index(fields=['timestamp', 'event_type'], name='audit_audit_timesta_a7623a_idx')],
            },
        ),
    ]
