# Generated by Django 5.1.15 on 2026-05-26 18:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('run_command', 'Run Command'), ('push_branch', 'Push Branch'), ('open_pr', 'Open PR'), ('install_package', 'Install Package'), ('network', 'Network'), ('deploy', 'Deploy'), ('cross_account_fork', 'Cross-Account Fork')], max_length=32)),
                ('risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('destructive', 'Destructive')], max_length=16)),
                ('summary', models.CharField(max_length=255)),
                ('preview', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('signed_nonce', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='threads.thread')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status'], name='approvals_a_status_06b2f0_idx'), models.Index(fields=['risk'], name='approvals_a_risk_3ed047_idx'), models.Index(fields=['expires_at'], name='approvals_a_expires_5c6822_idx')],
            },
        ),
    ]
