# Generated by Django 5.1.15 on 2026-05-26 18:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('hosts', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('runtime', models.CharField(max_length=64)),
                ('runtime_mode', models.CharField(choices=[('pty', 'PTY'), ('rc', 'Remote Control'), ('exec', 'Exec'), ('api', 'API')], default='pty', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('starting', 'Starting'), ('running', 'Running'), ('waiting_approval', 'Waiting Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=20)),
                ('external_session_ref', models.CharField(blank=True, max_length=1024)),
                ('worktree_path', models.CharField(blank=True, max_length=1024)),
                ('branch_name', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='accounts.account')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='hosts.host')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='projects.project')),
            ],
            options={
                'ordering': ['-last_event_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool'), ('slash', 'Slash'), ('system_event', 'System Event')], max_length=16)),
                ('content', models.TextField()),
                ('raw_content_encrypted', models.BinaryField(blank=True, null=True)),
                ('raw_retention_expires_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='threads.thread')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['status'], name='threads_thr_status_80da35_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['runtime'], name='threads_thr_runtime_d01600_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['host'], name='threads_thr_host_id_df0af7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'sequence'], name='threads_mes_thread__e13743_idx'),
        ),
    ]
