# Generated by Django 5.1.15 on 2026-05-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threads", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="content",
            new_name="redacted_content",
        ),
        migrations.AddField(
            model_name="thread",
            name="observed_jsonl_path",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="thread",
            name="runtime_mode",
            field=models.CharField(
                choices=[
                    ("pty", "PTY"),
                    ("rc", "Remote Control"),
                    ("exec", "Exec"),
                    ("api", "API"),
                    ("sdk", "Claude Agent (SDK)"),
                    ("observed", "Observed"),
                    ("openclaw", "OpenClaw"),
                    ("hermes", "Hermes"),
                ],
                default="pty",
                max_length=16,
            ),
        ),
    ]
