# Generated by Django 5.2.15 on 2026-06-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_rename_content_message_redacted_content_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['external_session_ref'], name='threads_thr_externa_704798_idx'),
        ),
    ]
