# Generated by Django 5.2.15 on 2026-07-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_thread_threads_thr_externa_704798_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='source_event_key',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('source_event_key__isnull', False)), fields=('thread', 'source_event_key'), name='unique_thread_source_event_key'),
        ),
    ]
