# Generated by Django 5.1.15 on 2026-05-26 18:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sensitivity_max', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('regulated', 'Regulated')], default='internal', max_length=16)),
                ('runtime_modes_allowed', models.JSONField(blank=True, default=list)),
                ('providers_allowed', models.JSONField(blank=True, default=list)),
                ('provider_jurisdictions_allowed', models.JSONField(blank=True, default=list)),
                ('account_orgs_allowed', models.JSONField(blank=True, default=list)),
                ('hosts_allowed', models.JSONField(blank=True, default=list)),
                ('egress_allowed', models.BooleanField(default=False)),
                ('rc_via_anthropic_allowed', models.BooleanField(default=False)),
                ('cloud_models_allowed', models.BooleanField(default=False)),
                ('data_classes_allowed', models.JSONField(blank=True, default=list)),
                ('raw_retention_max_days', models.PositiveIntegerField(default=0)),
                ('require_worktree', models.BooleanField(default=True)),
                ('require_approval_for', models.JSONField(blank=True, default=list)),
                ('block_destructive', models.BooleanField(default=True)),
                ('max_runtime_minutes', models.PositiveIntegerField(default=60)),
                ('max_parallel_threads', models.PositiveIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
