# Generated by Django 5.1.15 on 2026-05-26 18:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('auth_type', models.CharField(max_length=32)),
                ('credential_type', models.CharField(max_length=32)),
                ('encrypted_credential', models.BinaryField()),
                ('credential_key_id', models.CharField(max_length=255)),
                ('credential_recipient', models.CharField(max_length=255)),
                ('credential_scheme_version', models.PositiveIntegerField(default=1)),
                ('credential_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('credential_revoked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host_binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_accounts', to='hosts.host')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider'], name='accounts_ac_provide_ceab20_idx'), models.Index(fields=['credential_key_id'], name='accounts_ac_credent_661684_idx')],
            },
        ),
    ]
