# Generated by Django 5.1.15 on 2026-05-26 18:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdapterCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_available', models.BooleanField(default=False)),
                ('last_probed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adapter_capabilities', to='hosts.host')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'host')},
            },
        ),
    ]
