# Generated by Django 5.2.15 on 2026-07-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orc_setup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="setupstate",
            name="telegram_challenge",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
