"""Matrix surface service layer.

Mirrors apps/telegram/service.py conventions:
- get_or_create_thread_for_room  (sync, called via database_sync_to_async)
- is_approved                    (sync, pure settings check)
- handle_message                 (async, main entry point for the bot loop)
- deliver_prompt                 (async, called by the prompt-delivery machinery)
"""

import logging

from channels.db import database_sync_to_async
from django.conf import settings

from apps.accounts.models import Account
from apps.matrix.models import MatrixRoom
from apps.matrix.render import parse_reply, render_prompt
from apps.prompts.models import Prompt
from apps.prompts.service import resolve as resolve_prompt
from apps.threads.dispatch import dispatch_text
from apps.threads.models import Thread

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Thread / room bootstrap
# ---------------------------------------------------------------------------


def get_or_create_thread_for_room(room_id: str) -> Thread:
    existing = (
        MatrixRoom.objects.select_related("thread", "thread__account")
        .filter(room_id=room_id)
        .first()
    )
    if existing is not None:
        return existing.thread

    account, _ = Account.objects.get_or_create(
        provider="matrix",
        label="matrix",
        defaults={"auth_type": "none", "credential_type": "none"},
    )
    thread = Thread.objects.create(
        name=f"matrix:{room_id}",
        runtime="matrix",
        runtime_mode=Thread.RuntimeModeChoices.API,
        account=account,
    )
    MatrixRoom.objects.create(room_id=room_id, thread=thread)
    return thread


@database_sync_to_async
def _get_thread_with_account(thread_id) -> Thread:
    return Thread.objects.select_related("account").get(id=thread_id)


@database_sync_to_async
def _rebind_room(room_id: str, thread_id) -> None:
    """Point this Matrix room at a new thread (started by /openremote-control)."""
    MatrixRoom.objects.filter(room_id=room_id).update(thread_id=thread_id)


# ---------------------------------------------------------------------------
# Allowlist check
# ---------------------------------------------------------------------------


def is_approved(sender_mxid: str) -> bool:
    """Return True only if sender_mxid is in the exact MATRIX_APPROVED_MXIDS set.

    Anti-spoof note (v1 limitation): bridged/puppet MXIDs generated by
    mautrix-* look like @whatsapp_<phone>:server or @_slack_<uid>:server.
    These MUST NOT be added to MATRIX_APPROVED_MXIDS — only human operator
    MXIDs (@user:homeserver) should appear in the allowlist.  Future hardening:
    enforce a localpart prefix/namespace check (e.g. reject any MXID whose
    localpart starts with an underscore or contains a bridge namespace sigil).
    For now this is a pure exact-match lookup; operators own the list.
    """
    approved: list[str] = getattr(settings, "MATRIX_APPROVED_MXIDS", [])
    return sender_mxid in approved


# ---------------------------------------------------------------------------
# Pending-prompt lookup (sync helper)
# ---------------------------------------------------------------------------


def _get_pending_prompt(thread: Thread) -> Prompt | None:
    return (
        Prompt.objects.filter(thread=thread, status=Prompt.StatusChoices.PENDING)
        .order_by("-requested_at")
        .first()
    )


# ---------------------------------------------------------------------------
# Main message handler
# ---------------------------------------------------------------------------


async def handle_message(
    room_id: str,
    sender_mxid: str,
    text: str,
    *,
    send,
) -> None:
    """Handle an incoming Matrix room message.

    1. If there is a PENDING prompt on this thread:
       a. Try to parse the reply.
       b. For APPROVAL prompts, also check is_approved(sender_mxid).
       c. On success, resolve the prompt and send a confirmation.
       d. On authorisation failure, send 'not authorised'.
    2. Otherwise, treat as a chat message and dispatch_text.
    """
    try:
        thread = await database_sync_to_async(get_or_create_thread_for_room)(room_id)
        thread = await _get_thread_with_account(thread.id)

        prompt = await database_sync_to_async(_get_pending_prompt)(thread)

        if prompt is not None:
            kwargs = parse_reply(prompt, text)
            if kwargs is not None:
                needs_approval = prompt.trust_class == Prompt.TrustClass.APPROVAL
                if needs_approval and not is_approved(sender_mxid):
                    await send(room_id, "Not authorised.")
                    return

                _resolve = database_sync_to_async(resolve_prompt)
                result = await _resolve(prompt.nonce, by=sender_mxid, **kwargs)
                if result is not None:
                    await send(room_id, "Recorded.")
                else:
                    await send(room_id, "Expired or already answered.")
            # If kwargs is None the reply didn't match — fall through silently
            return

        # No pending prompt — treat as a chat message
        buffer = ""
        reply = ""
        new_thread_id = None

        async def on_event(data):
            nonlocal buffer, reply, new_thread_id
            etype = data.get("type")
            if etype == "message_delta":
                buffer += data.get("text", "")
            elif etype == "message_complete":
                reply = data.get("text") or buffer
            elif etype == "slash_result":
                reply = data.get("message", "")
                if data.get("new_thread_id"):
                    new_thread_id = data["new_thread_id"]
            elif etype == "error":
                reply = f"Error: {data.get('message', '')}"

        await dispatch_text(thread, text, on_event=on_event)

        if new_thread_id:
            await _rebind_room(room_id, new_thread_id)

        if reply:
            await send(room_id, reply)

    except Exception:
        logger.exception("matrix handle_message failed room=%s sender=%s", room_id, sender_mxid)


# ---------------------------------------------------------------------------
# Prompt delivery
# ---------------------------------------------------------------------------


async def deliver_prompt(room_id: str, prompt: Prompt, *, send) -> None:
    """Send a rendered prompt to the Matrix room (best-effort)."""
    try:
        rendered = render_prompt(prompt)
        await send(room_id, rendered)
    except Exception:
        logger.exception("matrix deliver_prompt failed room=%s", room_id)
