# Generated by Django 5.2.15 on 2026-06-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gatewaymessage',
            new_name='gateway_gat_platfor_46255d_idx',
            old_name='gateway_msg_platform_delivered_idx',
        ),
    ]
