# Generated by Django 5.1.15 on 2026-06-06 21:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threads', '0002_rename_content_message_redacted_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_type', models.CharField(choices=[('notice', 'Notice'), ('choice_single', 'Single Choice'), ('choice_multi', 'Multi Choice'), ('free_text', 'Free Text'), ('approval', 'Approval')], max_length=16)),
                ('trust_class', models.CharField(choices=[('informational', 'Informational'), ('decision', 'Decision'), ('approval', 'Approval')], default='decision', max_length=16)),
                ('question', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, default='')),
                ('options', models.JSONField(default=list)),
                ('min_choices', models.PositiveIntegerField(default=0)),
                ('max_choices', models.PositiveIntegerField(default=1)),
                ('nonce', models.CharField(db_index=True, max_length=64)),
                ('prompt_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('surface_message_ref', models.JSONField(default=dict)),
                ('response', models.JSONField(blank=True, null=True)),
                ('answered_by', models.CharField(blank=True, default='', max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='threads.thread')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
